services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: shared_pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - shared_pgadmin_data:/var/lib/pgadmin
    networks:
      - shared_pgadmin_network

volumes:
  shared_pgadmin_data:
    name: shared_pgadmin_data
networks:
  shared_pgadmin_network:
    name: shared_pgadmin_network
    driver: bridge